### ISSUE TITLE
Error When Trying to Store PropertyDTO with Type/Value Mismatch

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/resilient_async_cts#14]
Received this error

```
Exception in callback CustomThreatService.launch_new_search.<locals>.<lambda>(<Task finishe...o not match")>) at /Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/custom_threat_service.py:296
handle: <Handle CustomThreatService.launch_new_search.<locals>.<lambda>(<Task finishe...o not match")>) at /Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/custom_threat_service.py:296>
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/custom_threat_service.py", line 296, in <lambda>
    resp.add_done_callback(lambda future: self.search_complete_handler(future, search_id, artifact_payload.get("type"), artifact_payload.get("value"), file_payload, mongo))
  File "/Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/custom_threat_service.py", line 326, in search_complete_handler
    raise search_exception
  File "/Users/liammahoney/Documents/code/resilient_async_cts/test_cts/cts/cts.py", line 22, in searcher
    return await url_searcher(artifact_value)
  File "/Users/liammahoney/Documents/code/resilient_async_cts/test_cts/cts/searchers/url.py", line 22, in url_searcher
    return generate_url_hit(results)
  File "/Users/liammahoney/Documents/code/resilient_async_cts/test_cts/cts/searchers/url.py", line 36, in generate_url_hit
    artifact_property_dtos.append(ArtifactPropertyDTO('string', 'Malicious Score', url_data.get('score')))
  File "/Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/dto/artifact_property_dto.py", line 29, in __init__
    self.types_match(type, value)
  File "/Users/liammahoney/Documents/code/resilient_async_cts/resilient_async_cts/resilient_async_cts/dto/artifact_property_dto.py", line 55, in types_match
    raise ValueTypeMismatch(type, value)
resilient_async_cts.dto.artifact_property_dto.ValueTypeMismatch: (ValueTypeMismatch(...), "the type <class 'type'> and value 86 do not match")
Exception raised during execution of the search function for search id 6100c643779260e842231534. Removing the search_id entry from the Active Searches table and inserting emtpy hit into the Results table
```

While returning an ArtifactPropertyDTO whose value did not match the type specified. e.g.:

`ArtifactPropertyDTO('string', 'Malicious Score', 80))`.

This should be caught and handled better.

**Comment by LiamMahoney** [comment]
This was an exception being thrown from the `ArtifactPropertyDTO` class. I refactored the message that gets logged due to this to make it more clear it's somewhat expected - the developer needs to fix the issue in their implementation of the CTS.
