### ISSUE TITLE
codegen fails when the package is installed without -e 

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/resilient_async_cts#17]
When the package is pip installed without the `-e` flag, the codegen functionality is broken.

```
(.venv) liammahoney@Liams-MacBook-Pro cts % resilient_async_cts codegen -n virus_total
Generating boilerplate code.
Failed to generate boilerplate code. Cleaning up any partially built directories.
Traceback (most recent call last):
  File "/Users/liammahoney/Documents/code/cts/.venv/lib/python3.8/site-packages/resilient_async_cts/codegen/codegen.py", line 29, in codegen
    populate_dir(cts_dir, os.path.join(os.path.dirname(__file__), "template"), name=name, title_name=name.title())
  File "/Users/liammahoney/Documents/code/cts/.venv/lib/python3.8/site-packages/resilient_async_cts/codegen/codegen.py", line 78, in populate_dir
    dir_contents = os.listdir(template_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/liammahoney/Documents/code/cts/.venv/lib/python3.8/site-packages/resilient_async_cts/codegen/template'

Execution complete. Thanks for using resilient_async_cts
```

Fixed by uninstalling and installing with `-e` flag. Not ideal, need to figure out how to make this work when it's installed without the -e flag

**Comment by lmahoney1** [comment]
https://stackoverflow.com/a/39887784 should fix this issue.

Looks like this is what `resilient-sdk` does as well, here's that package's MANIFEST.in file - https://github.com/ibmresilient/resilient-python-api/blob/fe0111caa2017cf2031d2c8c4f45e234161bc7e6/resilient-sdk/MANIFEST.in

**Comment by LiamMahoney** [comment]
Had to create `MANIFEST.in` in the same level as `setup.py` with:

```
recursive-include resilient_async_cts/codegen/template *.jinja2
```

and add 

```python
...
    include_package_data=True,
...
```

to `setup.py`
